required = ["github.com/ovh/venom", "github.com/golang/lint/golint"]

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/loopfz/gadgeto"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "~1.9"

[[constraint]]
  name = "github.com/gin-gonic/contrib"
  branch = "master"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "~2.2"

[[constraint]]
  branch = "master"
  name = "github.com/juju/errors"
